version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile

    volumes:
      - /var/run/docker.sock:/var/run/docker-host.sock
      - ../..:/workspaces:cached
      - ./.zshrc:/home/vscode/.zshrc

    environment:
      GITHUB_NPM_TOKEN: "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"

    entrypoint: /usr/local/share/docker-init.sh
    command: sleep infinity
    user: vscode
